{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.projectName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.projectName }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Values.projectName }}
    apiVersion: apps/v1
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.averageUtilization }}
{{- end }}
